"""images table

Revision ID: 937292d86b65
Revises: 
Create Date: 2022-04-26 19:01:13.830625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937292d86b65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_image_location'), 'image', ['image_location'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_image_location'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
